@extends('admin.layout')
@php($editing=$offer->exists)
@section('title',$editing?'Edit offer':'Add offer') @section('heading',$editing?'Edit offer':'Add offer')
@section('content')
<div class="mb-5"><a class="text-sm text-[#9ca3ae] hover:text-white" href="{{ route('admin.offers.index') }}">← Back to offers</a></div>
@if($errors->any())<div class="mb-6 rounded-2xl border border-[#e5484d]/40 bg-[#e5484d]/10 p-4 text-sm text-[#ff8589]">{{ $errors->first() }}</div>@endif
<form method="POST" enctype="multipart/form-data" action="{{ $editing?route('admin.offers.update',$offer):route('admin.offers.store') }}" class="grid gap-6 xl:grid-cols-2">@csrf @if($editing)@method('PUT')@endif
<section class="admin-card space-y-5"><h2 class="font-bold">English content</h2><label><span class="admin-label">Title</span><input class="admin-input" name="title_en" value="{{ old('title_en',$offer->title_en) }}" required></label><label><span class="admin-label">Description</span><textarea class="admin-input" name="description_en" rows="4">{{ old('description_en',$offer->description_en) }}</textarea></label><label><span class="admin-label">Badge (optional)</span><input class="admin-input" name="badge_en" value="{{ old('badge_en',$offer->badge_en) }}" placeholder="Best value"></label></section>
<section class="admin-card space-y-5" dir="rtl"><h2 class="font-bold">المحتوى العربي</h2><label><span class="admin-label">العنوان</span><input class="admin-input text-right" name="title_ar" value="{{ old('title_ar',$offer->title_ar) }}" required></label><label><span class="admin-label">الوصف</span><textarea class="admin-input text-right" name="description_ar" rows="4">{{ old('description_ar',$offer->description_ar) }}</textarea></label><label><span class="admin-label">الشارة (اختياري)</span><input class="admin-input text-right" name="badge_ar" value="{{ old('badge_ar',$offer->badge_ar) }}" placeholder="أفضل قيمة"></label></section>
<section class="admin-card space-y-5 xl:col-span-2"><h2 class="font-bold">Pricing and availability</h2><div class="grid gap-5 md:grid-cols-4"><label><span class="admin-label">Price</span><input class="admin-input" type="number" step="0.01" min="0" name="price" value="{{ old('price',$offer->price) }}"></label><label><span class="admin-label">Original price</span><input class="admin-input" type="number" step="0.01" min="0" name="original_price" value="{{ old('original_price',$offer->original_price) }}"></label><label><span class="admin-label">Currency</span><input class="admin-input" name="currency" maxlength="8" value="{{ old('currency',$offer->currency??'USD') }}" required></label><label><span class="admin-label">Reward Gold</span><input class="admin-input" type="number" min="0" name="reward_coins" value="{{ old('reward_coins',$offer->reward_coins??0) }}" required></label><label><span class="admin-label">Image</span><input class="admin-input" type="file" name="image" accept="image/jpeg,image/png,image/webp"></label><label><span class="admin-label">Purchase/action value</span><input class="admin-input" name="action_value" value="{{ old('action_value',$offer->action_value) }}" placeholder="Product ID or URL"></label><label><span class="admin-label">Display order</span><input class="admin-input" type="number" min="0" name="sort_order" value="{{ old('sort_order',$offer->sort_order??0) }}" required></label><span></span><label><span class="admin-label">Starts at</span><input class="admin-input" type="datetime-local" name="starts_at" value="{{ old('starts_at',$offer->starts_at?->format('Y-m-d\TH:i')) }}"></label><label><span class="admin-label">Ends at</span><input class="admin-input" type="datetime-local" name="ends_at" value="{{ old('ends_at',$offer->ends_at?->format('Y-m-d\TH:i')) }}"></label></div><label class="flex items-center gap-2 text-sm"><input type="checkbox" class="accent-[#634bf7]" name="is_active" value="1" @checked(old('is_active',$offer->exists?$offer->is_active:true))> Active and eligible to display</label><div class="flex gap-3"><button class="admin-primary">{{ $editing?'Save offer':'Create offer' }}</button>@if($editing)<button form="delete-offer" type="button" onclick="if(confirm('Delete this offer?'))document.getElementById('delete-offer').submit()" class="admin-danger">Delete</button>@endif</div></section></form>
@if($editing)<form id="delete-offer" method="POST" action="{{ route('admin.offers.destroy',$offer) }}">@csrf @method('DELETE')</form>@endif
@endsection
