@extends('admin.layout')
@section('title','Manage room') @section('heading','Manage room')
@section('content')
<div class="mb-5"><a class="text-sm text-[#9ca3ae] hover:text-white" href="{{ route('admin.rooms.index') }}">← Back to rooms</a></div>
@if($errors->any())<div class="mb-6 rounded-2xl border border-[#e5484d]/40 bg-[#e5484d]/10 p-4 text-sm text-[#ff8589]">{{ $errors->first() }}</div>@endif
<div class="grid gap-6 xl:grid-cols-[1fr_400px]">
<section class="admin-card"><div class="mb-6"><h2 class="text-lg font-bold">{{ $room->name }}</h2><p class="font-mono text-xs text-[#9ca3ae]">Room ID {{ $room->public_id }} · Hosted by {{ $room->host->name }}</p></div><form method="POST" action="{{ route('admin.rooms.update',$room) }}" class="grid gap-5 sm:grid-cols-2">@csrf @method('PUT')<label class="sm:col-span-2"><span class="admin-label">Room name</span><input class="admin-input" name="name" value="{{ old('name',$room->name) }}" required></label><label><span class="admin-label">Language</span><select class="admin-input" name="language"><option @selected($room->language==='EN')>EN</option><option @selected($room->language==='AR')>AR</option></select></label><label><span class="admin-label">Category</span><select class="admin-input" name="tag">@foreach(['chatting','gaming','music','party'] as $tag)<option value="{{ $tag }}" @selected($room->tag===$tag)>{{ ucfirst($tag) }}</option>@endforeach</select></label><label><span class="admin-label">Maximum members</span><input class="admin-input" type="number" min="9" max="1000" name="max_members" value="{{ old('max_members',$room->max_members) }}"></label><div class="space-y-3 pt-7"><label class="flex gap-2 text-sm"><input type="checkbox" name="is_featured" value="1" class="accent-[#634bf7]" @checked($room->is_featured)> Featured room</label><label class="flex gap-2 text-sm"><input type="checkbox" name="is_locked" value="1" class="accent-[#f6810d]" @checked($room->is_locked)> Prevent new joins</label></div><div class="sm:col-span-2"><button class="admin-primary">Save room</button></div></form></section>
<aside class="space-y-6"><section class="admin-card"><h2 class="font-bold">Room status</h2><p class="mt-2 text-sm text-[#9ca3ae]">Closing removes all members except the host and releases their seats.</p><form class="mt-4" method="POST" action="{{ route('admin.rooms.closed',$room) }}">@csrf<button class="{{ $room->closed_at?'admin-secondary':'admin-danger' }} w-full">{{ $room->closed_at?'Reopen room':'Close room' }}</button></form></section><section class="admin-card"><h2 class="font-bold">Members · {{ $room->members->count() }}</h2><div class="mt-3 max-h-72 divide-y divide-[#2a3140] overflow-y-auto">@foreach($room->members as $member)<div class="flex items-center justify-between py-3"><div><strong class="text-sm">{{ $member->user->name }}</strong><small class="block text-[#9ca3ae]">{{ ucfirst($member->role) }}</small></div>@if($member->role!=='host')<form method="POST" action="{{ route('admin.rooms.members.destroy',[$room,$member]) }}">@csrf @method('DELETE')<button class="text-xs text-[#ff8589]">Remove</button></form>@endif</div>@endforeach</div></section></aside>
</div>
<section class="admin-card mt-6"><h2 class="mb-4 font-bold">Seats</h2><div class="grid grid-cols-3 gap-3 sm:grid-cols-5 lg:grid-cols-9">@foreach($room->seats as $seat)<div class="rounded-xl border border-[#2a3140] p-3 text-center"><div class="text-lg font-black">{{ $seat->position }}</div><div class="mt-1 truncate text-xs {{ $seat->is_locked?'text-[#ffb35b]':'text-[#9ca3ae]' }}">{{ $seat->is_locked?'Locked':($seat->user?->name??'Open') }}</div>@if($seat->position!==1)<form class="mt-2" method="POST" action="{{ route('admin.rooms.seats.toggle',[$room,$seat]) }}">@csrf<button class="text-xs text-[#7361e9]">{{ $seat->is_locked?'Unlock':'Lock' }}</button></form>@endif</div>@endforeach</div></section>
@endsection
