@extends('admin.layout')
@php($editing=$banner->exists)
@section('title',$editing?'Edit banner':'Add banner') @section('heading',$editing?'Edit banner':'Add banner')
@section('content')
<div class="mb-5"><a class="text-sm text-[#9ca3ae] hover:text-white" href="{{ route('admin.banners.index') }}">← Back to banners</a></div>
@if($errors->any())<div class="mb-6 rounded-2xl border border-[#e5484d]/40 bg-[#e5484d]/10 p-4 text-sm text-[#ff8589]">{{ $errors->first() }}</div>@endif
<form method="POST" enctype="multipart/form-data" action="{{ $editing?route('admin.banners.update',$banner):route('admin.banners.store') }}" class="grid gap-6 xl:grid-cols-2">@csrf @if($editing)@method('PUT')@endif
<section class="admin-card space-y-5"><h2 class="font-bold">English content</h2><label class="block"><span class="admin-label">Title</span><textarea class="admin-input" name="title_en" rows="2" required>{{ old('title_en',$banner->title_en) }}</textarea></label><label class="block"><span class="admin-label">Subtitle</span><textarea class="admin-input" name="subtitle_en" rows="3">{{ old('subtitle_en',$banner->subtitle_en) }}</textarea></label><label class="block"><span class="admin-label">Button label</span><input class="admin-input" name="cta_en" value="{{ old('cta_en',$banner->cta_en) }}"></label></section>
<section class="admin-card space-y-5" dir="rtl"><h2 class="font-bold">المحتوى العربي</h2><label class="block"><span class="admin-label">العنوان</span><textarea class="admin-input text-right" name="title_ar" rows="2" required>{{ old('title_ar',$banner->title_ar) }}</textarea></label><label class="block"><span class="admin-label">الوصف</span><textarea class="admin-input text-right" name="subtitle_ar" rows="3">{{ old('subtitle_ar',$banner->subtitle_ar) }}</textarea></label><label class="block"><span class="admin-label">نص الزر</span><input class="admin-input text-right" name="cta_ar" value="{{ old('cta_ar',$banner->cta_ar) }}"></label></section>
<section class="admin-card space-y-5 xl:col-span-2"><h2 class="font-bold">Display and action</h2><div class="grid gap-5 md:grid-cols-3"><label><span class="admin-label">Image (JPG, PNG, WebP)</span><input class="admin-input" type="file" name="image" accept="image/jpeg,image/png,image/webp"></label><label><span class="admin-label">Action</span><select class="admin-input" name="action_type">@foreach(['none','games','rooms','offers','url'] as $type)<option value="{{ $type }}" @selected(old('action_type',$banner->action_type??'none')===$type)>{{ ucfirst($type) }}</option>@endforeach</select></label><label><span class="admin-label">Action value / URL</span><input class="admin-input" name="action_value" value="{{ old('action_value',$banner->action_value) }}"></label><label><span class="admin-label">Display order</span><input class="admin-input" type="number" name="sort_order" min="0" value="{{ old('sort_order',$banner->sort_order??0) }}"></label><label><span class="admin-label">Starts at</span><input class="admin-input" type="datetime-local" name="starts_at" value="{{ old('starts_at',$banner->starts_at?->format('Y-m-d\TH:i')) }}"></label><label><span class="admin-label">Ends at</span><input class="admin-input" type="datetime-local" name="ends_at" value="{{ old('ends_at',$banner->ends_at?->format('Y-m-d\TH:i')) }}"></label></div><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" class="accent-[#634bf7]" @checked(old('is_active',$banner->exists?$banner->is_active:true))> Active and eligible to display</label><div class="flex gap-3"><button class="admin-primary">{{ $editing?'Save banner':'Create banner' }}</button>@if($editing)<button form="delete-banner" type="button" onclick="if(confirm('Delete this banner?'))document.getElementById('delete-banner').submit()" class="admin-danger">Delete</button>@endif</div></section></form>
@if($editing)<form id="delete-banner" method="POST" action="{{ route('admin.banners.destroy',$banner) }}">@csrf @method('DELETE')</form>@endif
@endsection
