@extends('admin.layout')
@section('title','App settings') @section('heading','App settings')
@section('content')
@if($errors->any())<div class="mb-6 rounded-2xl border border-[#e5484d]/40 bg-[#e5484d]/10 p-4 text-sm text-[#ff8589]">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('admin.settings.update') }}" class="grid gap-6 xl:grid-cols-2">@csrf @method('PUT')
<section class="admin-card space-y-5 xl:col-span-2"><h2 class="font-bold">Availability</h2><div class="grid gap-4 md:grid-cols-3"><label class="flex items-start gap-3 rounded-xl border border-[#2a3140] p-4"><input type="checkbox" class="mt-1 accent-[#634bf7]" name="registration_enabled" value="1" @checked(old('registration_enabled',$settings->registration_enabled))><span><strong class="block text-sm">Allow registration</strong><small class="text-[#9ca3ae]">New users can create accounts.</small></span></label><label class="flex items-start gap-3 rounded-xl border border-[#2a3140] p-4"><input type="checkbox" class="mt-1 accent-[#f6810d]" name="maintenance_enabled" value="1" @checked(old('maintenance_enabled',$settings->maintenance_enabled))><span><strong class="block text-sm">Maintenance notice</strong><small class="text-[#9ca3ae]">Tell the app maintenance is active.</small></span></label><label class="flex items-start gap-3 rounded-xl border border-[#2a3140] p-4"><input type="checkbox" class="mt-1 accent-[#e5484d]" name="force_update" value="1" @checked(old('force_update',$settings->force_update))><span><strong class="block text-sm">Force app update</strong><small class="text-[#9ca3ae]">Use only with minimum versions.</small></span></label></div></section>
<section class="admin-card space-y-5"><h2 class="font-bold">Maintenance message</h2><label><span class="admin-label">English</span><textarea class="admin-input" rows="4" name="maintenance_message_en">{{ old('maintenance_message_en',$settings->maintenance_message_en) }}</textarea></label><label dir="rtl"><span class="admin-label">العربية</span><textarea class="admin-input text-right" rows="4" name="maintenance_message_ar">{{ old('maintenance_message_ar',$settings->maintenance_message_ar) }}</textarea></label></section>
<section class="admin-card space-y-5"><h2 class="font-bold">App versions</h2><label><span class="admin-label">Minimum Android version</span><input class="admin-input" name="minimum_android_version" value="{{ old('minimum_android_version',$settings->minimum_android_version) }}" placeholder="1.0.0"></label><label><span class="admin-label">Minimum iOS version</span><input class="admin-input" name="minimum_ios_version" value="{{ old('minimum_ios_version',$settings->minimum_ios_version) }}" placeholder="1.0.0"></label><p class="text-xs text-[#9ca3ae]">The mobile app will enforce these values after its update-check screen is implemented.</p></section>
<section class="admin-card space-y-5 xl:col-span-2"><h2 class="font-bold">Support and legal links</h2><div class="grid gap-5 md:grid-cols-2"><label><span class="admin-label">Support email</span><input class="admin-input" type="email" name="support_email" value="{{ old('support_email',$settings->support_email) }}"></label><label><span class="admin-label">Support URL</span><input class="admin-input" type="url" name="support_url" value="{{ old('support_url',$settings->support_url) }}"></label><label><span class="admin-label">Terms URL</span><input class="admin-input" type="url" name="terms_url" value="{{ old('terms_url',$settings->terms_url) }}"></label><label><span class="admin-label">Privacy URL</span><input class="admin-input" type="url" name="privacy_url" value="{{ old('privacy_url',$settings->privacy_url) }}"></label></div><button class="admin-primary">Save app settings</button></section>
<section class="admin-card space-y-5 xl:col-span-2"><div><h2 class="font-bold">Room economy</h2><p class="mt-1 text-sm text-[#9ca3ae]">Server-authoritative treasure chest controls. Changes apply to new claims immediately.</p></div><div class="grid gap-5 md:grid-cols-2"><label><span class="admin-label">Gold per chest</span><input class="admin-input" type="number" min="1" max="100000" name="room_reward_gold" value="{{ old('room_reward_gold',$settings->room_reward_gold) }}" required></label><label><span class="admin-label">Cooldown in minutes</span><input class="admin-input" type="number" min="1" max="10080" name="room_reward_cooldown_minutes" value="{{ old('room_reward_cooldown_minutes',$settings->room_reward_cooldown_minutes) }}" required></label></div><p class="text-xs text-[#f4b860]">Existing countdowns keep their current unlock time; the new cooldown applies after the next claim.</p></section>
</form>
@endsection
